BOARD_TAG    = mega2560 # Here goes your board type, e.g. : uno
ARDUINO_PORT = /dev/ttyUSB1 # Change to your own tty interface

ARDUINO_LIBS = # The libs needed by your sketchbook, examples are : Wire Wire/utility Ethernet...

include Arduino.mk # This is where arduino-mk installed
